import Foundation
import Combine

class DataStore: ObservableObject {

    @Published var funds:   [Fund]             = []
    @Published var records: [InvestmentRecord] = []

    private static let fundsURL   = docURL("funds_v4.json")
    private static let recordsURL = docURL("records_v1.json")

    init() {
        load()
        if funds.isEmpty { seedDefaultFunds() }
        autoGenerateTodayRecords()
        refreshHoldingCosts()
    }

    func load() {
        funds   = decode([Fund].self,             from: DataStore.fundsURL)   ?? []
        records = decode([InvestmentRecord].self, from: DataStore.recordsURL) ?? []
    }

    func save() {
        encode(funds,   to: DataStore.fundsURL)
        encode(records, to: DataStore.recordsURL)
    }

    // MARK: 记录 CRUD
    func addRecord(_ r: InvestmentRecord) {
        records.append(r); save(); refreshHoldingCosts()
    }
    func updateRecord(_ r: InvestmentRecord) {
        if let i = records.firstIndex(where: { $0.id == r.id }) {
            records[i] = r; save(); refreshHoldingCosts()
        }
    }
    func deleteRecord(id: UUID) {
        records.removeAll { $0.id == id }; save(); refreshHoldingCosts()
    }

    // MARK: 自动计算累计投入（成功+部分成交记录之和；manualCost 设置后优先使用）
    func refreshHoldingCosts() {
        for i in funds.indices {
            if let manual = funds[i].manualCost {
                funds[i].holdingCost = manual
            } else {
                funds[i].holdingCost = records
                    .filter { $0.fundID == funds[i].id && ($0.status == .success || $0.status == .partial) }
                    .reduce(0) { $0 + $1.actualAmount }
            }
        }
        save()
    }

    // MARK: 基金更新
    func updateFund(_ f: Fund) {
        if let i = funds.firstIndex(where: { $0.id == f.id }) { funds[i] = f; save() }
    }
    func updateHoldingValue(fundID: UUID, holdingValue: Double, manualCost: Double? = nil) {
        if let i = funds.firstIndex(where: { $0.id == fundID }) {
            funds[i].holdingValue = holdingValue
            funds[i].manualCost   = manualCost
            funds[i].holdingCost  = manualCost ?? funds[i].holdingCost
            save()
        }
    }
    func updateETFHolding(fundID: UUID, holdingShares: Int, averageCost: Double) {
        if let i = funds.firstIndex(where: { $0.id == fundID }) {
            funds[i].holdingShares = holdingShares
            funds[i].averageCost   = averageCost
            save()
        }
    }

    // MARK: 查询
    func fundsForToday() -> [Fund] {
        let day = currentISOWeekday()
        return funds.filter { $0.scheduleDays.contains(day) }
    }
    func record(for fund: Fund, on date: Date) -> InvestmentRecord? {
        let cal = Calendar.current
        return records.first { $0.fundID == fund.id && cal.isDate($0.date, inSameDayAs: date) }
    }
    func records(for fund: Fund) -> [InvestmentRecord] {
        records.filter { $0.fundID == fund.id }.sorted { $0.date > $1.date }
    }
    func fund(for id: UUID) -> Fund? { funds.first { $0.id == id } }

    // 按月分组某基金的记录
    func recordsByMonth(for fund: Fund) -> [(String, [InvestmentRecord])] {
        let recs = records(for: fund)
        let cal  = Calendar.current
        let fmt  = DateFormatter(); fmt.locale = Locale(identifier: "zh_CN"); fmt.dateFormat = "yyyy年M月"
        var dict: [String: [InvestmentRecord]] = [:]
        for r in recs {
            let key = fmt.string(from: r.date)
            dict[key, default: []].append(r)
        }
        return dict.sorted { a, b in
            // 按时间倒序
            let fa = dict[a.key]!.first!.date
            let fb = dict[b.key]!.first!.date
            return fa > fb
        }
    }

    // MARK: 自动生成今日待确认记录
    func autoGenerateTodayRecords() {
        let today = Date()
        for fund in fundsForToday() where record(for: fund, on: today) == nil {
            records.append(InvestmentRecord(
                fundID: fund.id, date: today,
                plannedAmount: fund.isETF ? 0 : fund.dcaAmount,
                actualAmount:  fund.isETF ? 0 : fund.dcaAmount,
                status: .pending, isAutoGenerated: true))
        }
        save()
    }

    // MARK: 种子
    private func seedDefaultFunds() {
        funds = [
            Fund(name: "标普500ETF联接",        code: "513500", colorHex: "FF2C6FED",
                 scheduleDays: [1], dcaAmount: 0,   isETF: true,  etfTime: "14:50", etfLots: 1,
                 targetMinPct: 0.20, targetMaxPct: 0.30),
            Fund(name: "天弘中证红利低波100A",   code: "008114", colorHex: "FFFF6B35",
                 scheduleDays: [2], dcaAmount: 250, isETF: false,
                 targetMinPct: 0.18, targetMaxPct: 0.28),
            Fund(name: "易方达增强回报债券A",     code: "110017", colorHex: "FF34C759",
                 scheduleDays: [2], dcaAmount: 300, isETF: false, isRebalanceTarget: false),
            Fund(name: "华安黄金ETF联接A",       code: "000216", colorHex: "FFFFCC00",
                 scheduleDays: [2], dcaAmount: 100, isETF: false, isRebalanceTarget: false),
            Fund(name: "易方达中证A500ETF联接A", code: "022459", colorHex: "FFAF52DE",
                 scheduleDays: [2], dcaAmount: 200, isETF: false,
                 targetMinPct: 0.13, targetMaxPct: 0.22),
        ]
        save()
    }

    private static func docURL(_ name: String) -> URL {
        FileManager.default.urls(for: .documentDirectory, in: .userDomainMask)[0]
            .appendingPathComponent(name)
    }
    private func decode<T: Decodable>(_ t: T.Type, from url: URL) -> T? {
        guard let data = try? Data(contentsOf: url) else { return nil }
        let d = JSONDecoder(); d.dateDecodingStrategy = .iso8601
        return try? d.decode(t, from: data)
    }
    private func encode<T: Encodable>(_ v: T, to url: URL) {
        let e = JSONEncoder(); e.dateEncodingStrategy = .iso8601
        guard let data = try? e.encode(v) else { return }
        try? data.write(to: url, options: .atomicWrite)
    }
    private func currentISOWeekday() -> Int {
        let w = Calendar.current.component(.weekday, from: Date()); return w == 1 ? 7 : w - 1
    }
}
