import Foundation
import Combine

class DataStore: ObservableObject {

    @Published var funds:   [Fund]             = []
    @Published var records: [InvestmentRecord] = []

    private static let fundsURL   = docURL("funds_v2.json")
    private static let recordsURL = docURL("records_v1.json")

    init() {
        load()
        if funds.isEmpty { seedDefaultFunds() }
        autoGenerateTodayRecords()
    }

    // MARK: 持久化
    func load() {
        funds   = decode([Fund].self,             from: DataStore.fundsURL)   ?? []
        records = decode([InvestmentRecord].self, from: DataStore.recordsURL) ?? []
    }

    func save() {
        encode(funds,   to: DataStore.fundsURL)
        encode(records, to: DataStore.recordsURL)
    }

    // MARK: 记录增删改
    func addRecord(_ r: InvestmentRecord) {
        records.append(r)
        save()
    }

    func updateRecord(_ r: InvestmentRecord) {
        if let i = records.firstIndex(where: { $0.id == r.id }) {
            records[i] = r
            save()
        }
    }

    func deleteRecord(id: UUID) {
        records.removeAll { $0.id == id }
        save()
    }

    // MARK: 基金配置 + 持仓更新
    func updateFund(_ f: Fund) {
        if let i = funds.firstIndex(where: { $0.id == f.id }) {
            funds[i] = f
            save()
        }
    }

    // MARK: 今日应操作的基金
    func fundsForToday() -> [Fund] {
        let day = currentISOWeekday()
        return funds.filter { $0.scheduleDays.contains(day) }
    }

    // MARK: 某天某基金的记录
    func record(for fund: Fund, on date: Date) -> InvestmentRecord? {
        let cal = Calendar.current
        return records.first {
            $0.fundID == fund.id && cal.isDate($0.date, inSameDayAs: date)
        }
    }

    // MARK: 按日期分组（降序）
    var recordsByDate: [(Date, [InvestmentRecord])] {
        let cal = Calendar.current
        var dict: [Date: [InvestmentRecord]] = [:]
        for r in records {
            let day = cal.startOfDay(for: r.date)
            dict[day, default: []].append(r)
        }
        return dict.sorted { $0.key > $1.key }
    }

    func fund(for id: UUID) -> Fund? { funds.first { $0.id == id } }

    // MARK: 自动生成今日待确认记录
    func autoGenerateTodayRecords() {
        let today = Date()
        for fund in fundsForToday() {
            if record(for: fund, on: today) == nil {
                let r = InvestmentRecord(
                    fundID: fund.id,
                    date: today,
                    plannedAmount: fund.isETF ? 0 : fund.dcaAmount,
                    actualAmount: fund.isETF ? 0 : fund.dcaAmount,
                    status: .pending,
                    isAutoGenerated: true
                )
                records.append(r)
            }
        }
        save()
    }

    // MARK: 持仓快捷更新（从 holdingValue 编辑）
    func updateHolding(fundID: UUID, holdingValue: Double, holdingCost: Double,
                       holdingLots: Int, averageCost: Double) {
        if let i = funds.firstIndex(where: { $0.id == fundID }) {
            funds[i].holdingValue = holdingValue
            funds[i].holdingCost  = holdingCost
            funds[i].holdingLots  = holdingLots
            funds[i].averageCost  = averageCost
            save()
        }
    }

    // MARK: 总持仓市值
    var totalHoldingValue: Double { funds.reduce(0) { $0 + $1.holdingValue } }
    var totalHoldingCost:  Double { funds.reduce(0) { $0 + $1.holdingCost  } }

    // MARK: 种子数据
    private func seedDefaultFunds() {
        funds = [
            Fund(
                name: "标普500ETF联接",
                code: "513500",
                colorHex: "FF2C6FED",
                scheduleDays: [1],
                dcaAmount: 0,
                isETF: true,
                etfTime: "14:50",
                etfLots: 100,
                targetMinPct: 0.20,
                targetMaxPct: 0.30
            ),
            Fund(
                name: "天弘中证红利低波100A",
                code: "008114",
                colorHex: "FFFF6B35",
                scheduleDays: [2],
                dcaAmount: 250,
                isETF: false,
                targetMinPct: 0.18,
                targetMaxPct: 0.28
            ),
            Fund(
                name: "易方达增强回报债券A",
                code: "110017",
                colorHex: "FF34C759",
                scheduleDays: [2],
                dcaAmount: 300,
                isETF: false,
                isRebalanceTarget: false
            ),
            Fund(
                name: "华安黄金ETF联接A",
                code: "000216",
                colorHex: "FFFFCC00",
                scheduleDays: [2],
                dcaAmount: 100,
                isETF: false,
                isRebalanceTarget: false
            ),
            Fund(
                name: "易方达中证A500ETF联接A",
                code: "022459",
                colorHex: "FFAF52DE",
                scheduleDays: [2],          // 改为周二
                dcaAmount: 200,
                isETF: false,
                targetMinPct: 0.13,
                targetMaxPct: 0.22
            ),
        ]
        save()
    }

    // MARK: Codable 辅助
    private static func docURL(_ name: String) -> URL {
        FileManager.default
            .urls(for: .documentDirectory, in: .userDomainMask)[0]
            .appendingPathComponent(name)
    }
    private func decode<T: Decodable>(_ t: T.Type, from url: URL) -> T? {
        guard let data = try? Data(contentsOf: url) else { return nil }
        let d = JSONDecoder(); d.dateDecodingStrategy = .iso8601
        return try? d.decode(t, from: data)
    }
    private func encode<T: Encodable>(_ v: T, to url: URL) {
        let e = JSONEncoder(); e.dateEncodingStrategy = .iso8601
        guard let data = try? e.encode(v) else { return }
        try? data.write(to: url, options: .atomicWrite)
    }
    private func currentISOWeekday() -> Int {
        let w = Calendar.current.component(.weekday, from: Date())
        return w == 1 ? 7 : w - 1
    }
}
