import Foundation
import SwiftUI

struct Fund: Identifiable, Codable, Equatable {
    var id: UUID = UUID()
    var name: String
    var code: String
    var colorHex: String
    var scheduleDays: [Int]
    var dcaAmount: Double
    var isETF: Bool
    var etfTime: String?
    var etfLots: Int?             // 计划每次买入手数（用于任务展示）
    var targetMinPct: Double?
    var targetMaxPct: Double?
    var isRebalanceTarget: Bool = true

    // 持仓（自动/手动）
    var holdingCost: Double  = 0   // 累计投入，自动从记录计算（或由 manualCost 覆盖）
    var manualCost: Double?  = nil // 用户手动设置的累计投入（优先于自动计算）
    var holdingValue: Double = 0   // 场外基金当前市值（用户从券商同步）
    var holdingShares: Int   = 0   // 场内ETF持股数（股，非手）
    var averageCost: Double  = 0   // 场内ETF成本价（元/股）

    var color: Color { Color(hex: colorHex) ?? .blue }
    var scheduleText: String {
        let days = ["","周一","周二","周三","周四","周五","周六","周日"]
        return scheduleDays.map { days[$0] }.joined(separator: "、")
    }
    var actionText: String {
        if isETF, let time = etfTime, let lots = etfLots {
            return "\(time) 限时卖一价买入 \(lots) 手"
        }
        return "定投 \(Int(dcaAmount)) 元"
    }
}

enum RecordStatus: String, Codable, CaseIterable {
    case pending = "待确认"
    case success = "成功"
    case failed  = "余额不足"
    case partial = "部分成交"
    case skipped = "跳过"
}
extension RecordStatus {
    var color: Color {
        switch self {
        case .pending: return .orange
        case .success: return .green
        case .failed:  return .red
        case .partial: return .orange
        case .skipped: return Color(.systemGray)
        }
    }
    var icon: String {
        switch self {
        case .pending: return "clock.fill"
        case .success: return "checkmark.circle.fill"
        case .failed:  return "exclamationmark.circle.fill"
        case .partial: return "circle.lefthalf.filled"
        case .skipped: return "minus.circle.fill"
        }
    }
}

struct InvestmentRecord: Identifiable, Codable {
    var id: UUID = UUID()
    var fundID: UUID
    var date: Date
    var plannedAmount: Double
    var actualAmount: Double
    var units: Double?
    var price: Double?
    var status: RecordStatus
    var note: String?
    var isAutoGenerated: Bool = false
}

extension Color {
    init?(hex: String) {
        var h = hex.trimmingCharacters(in: .alphanumerics.inverted)
        if h.count == 6 { h = "FF" + h }
        guard h.count == 8, let val = UInt64(h, radix: 16) else { return nil }
        self.init(.sRGB,
            red:     Double((val >> 16) & 0xFF) / 255,
            green:   Double((val >>  8) & 0xFF) / 255,
            blue:    Double( val        & 0xFF) / 255,
            opacity: Double((val >> 24) & 0xFF) / 255)
    }
}
